clocksource: whitelist asm9260_timer driver for ARM
For now it is easier to allow only tested platforms, instead of
fighting with different platform specific issues.

This patch is fixing compile error on ARCH=SPARC and SPARC64:

Building sparc64:allmodconfig ... failed
--------------
Error log:
drivers/built-in.o: In function `asm9260_timer_init':
asm9260_timer.c:(.init.text+0x60d4): undefined reference to `of_io_request_and_map'

Tested-by: Guenter Roeck <linux@roeck-us.net>
Reported-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Oleksij Rempel <linux@rempel-privat.de>