ARM: clocksource: fix compile of asm9260_timer driver on ARCH=parisc
make sure this driver depends on GENERIC_CLOCKEVENTS

compiler error was found by kbuild test robot:

>> drivers/clocksource/asm9260_timer.c:114:14: warning: its scope is only this definition or declaration, which is probably not what you want
>> drivers/clocksource/asm9260_timer.c:124:16: warning: 'struct clock_event_device' declared inside parameter list
            struct clock_event_device *evt)

>> drivers/clocksource/asm9260_timer.c:124:16: warning: 'enum clock_event_mode' declared inside parameter list
>> drivers/clocksource/asm9260_timer.c:123:58: error: parameter 1 ('mode') has incomplete type
    static void asm9260_timer_set_mode(enum clock_event_mode mode,

Signed-off-by: Oleksij Rempel <linux@rempel-privat.de>